let arrayOfAnswers = [
    {
        letters: {
            middle: "A",
            otherSix: ["C", "F", "I", "L", "R", "Y"]
        },
        answers: {
            ACACIA: 1,
            ACAI: 1,
            ACRYLIC: 1,
            ACYCLIC: 1,
            AFAR: 1,
            AFFAIR: 1,
            AFFRAY: 1,
            AIRILY: 1,
            AIRY: 1,
            ALFALFA: 1,
            ALLAY: 1,
            ALLY: 1,
            ARIA: 1,
            ARIL: 1,
            ARRAY: 1,
            CALCIFY: 1,
            CALF: 1,
            CALL: 1,
            CALLA: 1,
            CARRY: 1,
            CARRYALL: 1,
            CILIA: 1,
            CIRCA: 1,
            CLARIFY: 1,
            CLAY: 1,
            CYCLICAL: 1,
            CYCLICALLY: 1,
            FACIAL: 1,
            FACIALLY: 1,
            FAIL: 1,
            FAIR: 1,
            FAIRLY: 1,
            FAIRY: 1,
            FALL: 1,
            FALLACY: 1,
            FARCICAL: 1,
            FARCICALLY: 1,
            FILIAL: 1,
            FILIALLY: 1,
            FLAIL: 1,
            FLAIR: 1,
            FLAY: 1,
            FRAIL: 1,
            FRAY: 1,
            FRIAR: 1,
            FRIARY: 1,
            LACY: 1,
            LAIC: 1,
            LAICAL: 1,
            LAIR: 1,
            LIAR: 1,
            LILAC: 1,
            LIRA: 1,
            LYRICAL: 1,
            LYRICALLY: 1,
            RACIAL: 1,
            RACIALLY: 1,
            RACY: 1,
            RAIL: 1,
            RAILCAR: 1,
            RALLY: 1,
            RIAL: 1,
            RIFFRAFF: 1,
            RIYAL: 1
        }
    },
    {
        letters: {
            middle: "A",
            otherSix: ["B", "I", "L", "T", "V", "Y"]
        },
        answers: {
            ABILITY: 1,
            ABLY: 1,
            ALIBI: 1,
            ALIT: 1,
            ALLAY: 1,
            ALLY: 1,
            ATILT: 1,
            AVAIL: 1,
            AVAILABILITY: 1,
            AVAILABLY: 1,
            BABA: 1,
            BABY: 1,
            BAIL: 1,
            BAIT: 1,
            BALL: 1,
            BATTY: 1,
            BIALY: 1,
            BILABIAL: 1,
            BLAB: 1,
            BLABBY: 1,
            BLAT: 1,
            LABIA: 1,
            LABIAL: 1,
            LAITY: 1,
            LAVA: 1,
            LIABILITY: 1,
            LIVABILITY: 1,
            TABBY: 1,
            TABLA: 1,
            TAIL: 1,
            TALI: 1,
            TALL: 1,
            TALLY: 1,
            TATTY: 1,
            TIBIA: 1,
            TIBIAL: 1,
            VIABILITY: 1,
            VIABLY: 1,
            VIAL: 1,
            VILLA: 1,
            VITAL: 1,
            VITALITY: 1,
            VITALLY: 1

        }
    },
    {
        letters: {
            middle: "O",
            otherSix: ["A", "F", "H", "L", "T", "Y"]
        },
        answers: {
            AFLOAT: 1,
            AFOOT: 1,
            AHOY: 1,
            ALLOT: 1,
            ALLOY: 1,
            ALOFT: 1,
            ALOHA: 1,
            ALOOF: 1,
            ALOOFLY: 1,
            ALTO: 1,
            ATOLL: 1,
            AYATOLLAH: 1,
            FALLOFF: 1,
            FLATFOOT: 1,
            FLOAT: 1,
            FLOATY: 1,
            FOAL: 1,
            FOLLY: 1,
            FOOL: 1,
            FOOT: 1,
            FOOTFALL: 1,
            HALO: 1,
            HAYLOFT: 1,
            HOLLY: 1,
            HOLT: 1,
            HOLY: 1,
            HOOF: 1,
            HOOT: 1,
            HOTFOOT: 1,
            HOTLY: 1,
            LAYOFF: 1,
            LOAF: 1,
            LOATH: 1,
            LOATHLY: 1,
            LOFT: 1,
            LOFTY: 1,
            LOLL: 1,
            LOOFA: 1,
            LOOFAH: 1,
            LOOT: 1,
            LOTTO: 1,
            LOYAL: 1,
            LOYALLY: 1,
            LOYALTY: 1,
            OATH: 1,
            OATY: 1,
            OFFAL: 1,
            TALLYHO: 1,
            TATTOO: 1,
            TOLL: 1,
            TOOL: 1,
            TOOT: 1,
            TOOTH: 1,
            TOOTHY: 1,
            TOTAL: 1,
            TOTALLY: 1,
            YAHOO: 1,
            YOOHOO: 1
        }
    },
    {
        letters: {
            middle: "D",
            otherSix: ["A", "L", "N", "R", "U", "Y"]
        },
        answers: {
            DADDY: 1,
            DALLY: 1,
            DANDY: 1,
            DARN: 1,
            DRAY: 1,
            DRYAD: 1,
            DRYLAND: 1,
            DRYLY: 1,
            DUAL: 1,
            DUALLY: 1,
            DULL: 1,
            DULLARD: 1,
            DULLY: 1,
            DULY: 1,
            DYAD: 1,
            LADY: 1,
            LAND: 1,
            LANDAU: 1,
            LANDLADY: 1,
            LANYARD: 1,
            LARD: 1,
            LAUD: 1,
            LAUNDRY: 1,
            NADA: 1,
            RADAR: 1,
            RAND: 1,
            RANDY: 1,
            RUDDY: 1,
            UNDULY: 1,
            YARD: 1
        }
    },
    {
        letters: {
            middle: "H",
            otherSix: ["A", "C", "D", "N", "O", "W"]
        },
        answers: {
            ACHOO: 1,
            ANCHO: 1,
            CHAD: 1,
            CHAW: 1,
            CHOW: 1,
            COACH: 1,
            COHO: 1,
            CONCH: 1,
            COWHAND: 1,
            DACHA: 1,
            HAND: 1,
            HODAD: 1,
            HONCHO: 1,
            HOOCH: 1,
            HOOD: 1,
            HOODOO: 1,
            HOWDAH: 1,
            NACHO: 1,
            NOHOW: 1,
            WAHOO: 1,
            WHOA: 1,
            WOOHOO: 1
        }
    },
    {
        letters: {
            middle: "T",
            otherSix: ["H", "I", "L", "M", "N", "O"]
        },
        answers: {
            HILT: 1,
            HINT: 1,
            HOLT: 1,
            HOOT: 1,
            INTO: 1,
            LILT: 1,
            LIMIT: 1,
            LINT: 1,
            LITHO: 1,
            LOOT: 1,
            LOTION: 1,
            LOTTO: 1,
            MILLIONTH: 1,
            MINT: 1,
            MITT: 1,
            MOLT: 1,
            MONOLITH: 1,
            MONTH: 1,
            MOONLIT: 1,
            MOOT: 1,
            MOTH: 1,
            MOTION: 1,
            MOTTO: 1,
            NINTH: 1,
            NOTION: 1,
            OMIT: 1,
            ONTO: 1,
            THIN: 1,
            TILL: 1,
            TILT: 1,
            TINT: 1,
            TOIL: 1,
            TOLL: 1,
            TOMTIT: 1,
            TOOL: 1,
            TOON: 1,
            TOOT: 1,
            TOOTH: 1
        }
    },
    {
        letters: {
            middle: "M",
            otherSix: ["A", "D", "G", "I", "P", "R"]
        },
        answers: {
            AMID: 1,
            ARMADA: 1,
            DAMP: 1,
            DIAGRAM: 1,
            DRAM: 1,
            DRAMA: 1,
            GAMMA: 1,
            GIMP: 1,
            GRAM: 1,
            GRAMMA: 1,
            GRAMMAR: 1,
            GRAMP: 1,
            GRAMPA: 1,
            GRIM: 1,
            IMAM: 1,
            IMPAIR: 1,
            MADAM: 1,
            MAGI: 1,
            MAGMA: 1,
            MAID: 1,
            MAIM: 1,
            MAMA: 1,
            MAMMA: 1,
            MARM: 1,
            MIDAIR: 1,
            MIDI: 1,
            PAMPA: 1,
            PARADIGM: 1,
            PIMP: 1,
            PRAM: 1,
            PRIM: 1,
            PRIMP: 1,
            RAMADA: 1,
            RAMP: 1
        }
    },
    {
        letters: {
            middle: "B",
            otherSix: ["A", "C", "I", "K", "R", "T"]
        },
        answers: {
            ABACI: 1,
            ABACK: 1,
            ARABICA: 1,
            BABA: 1,
            BABKA: 1,
            BACCARAT: 1,
            BACK: 1,
            BACKBIT: 1,
            BACKTRACK: 1,
            BAIT: 1,
            BARB: 1,
            BARBARIC: 1,
            BARIATRIC: 1,
            BARK: 1,
            BARRACK: 1,
            BATIK: 1,
            BICARB: 1,
            BRAT: 1,
            BRIAR: 1,
            BRICK: 1,
            BRICKBAT: 1,
            CARB: 1,
            CIABATTA: 1,
            CRAB: 1,
            CRIB: 1,
            KICKBACK: 1,
            RABBI: 1,
            RABBIT: 1,
            TIBIA: 1
        }
    },
    {
        letters: {
            middle: "A",
            otherSix: ["B", "E", "G", "M", "T", "Y"]
        },
        answers: {
            ABATE: 1,
            ABBEY: 1,
            ABEAM: 1,
            ABET: 1,
            AGATE: 1,
            AMEBA: 1,
            AMEBAE: 1,
            BABA: 1,
            BABE: 1,
            BABY: 1,
            BAGGAGE: 1,
            BAGGY: 1,
            BATE: 1,
            BATTY: 1,
            BEAM: 1,
            BEAT: 1,
            BEGAT: 1,
            BETA: 1,
            GABBY: 1,
            GAGA: 1,
            GAGE: 1,
            GAME: 1,
            GAMETE: 1,
            GAMMA: 1,
            GAMY: 1,
            GATE: 1,
            MAGE: 1,
            MAGMA: 1,
            MAMA: 1,
            MAMBA: 1,
            MAMMA: 1,
            MATE: 1,
            MATEY: 1,
            MATTE: 1,
            MAYBE: 1,
            MEAT: 1,
            MEATY: 1,
            MEGA: 1,
            MEGABYTE: 1,
            META: 1,
            TABBY: 1,
            TAME: 1,
            TATTY: 1,
            TEAM: 1,
            TEAMMATE: 1,
            TEAT: 1
        }
    },
    {
        letters: {
            middle: "M",
            otherSix: ["A", "C", "H", "N", "O", "R"]
        },
        answers: {
            AMMO: 1,
            ANCHORMAN: 1,
            ARMOR: 1,
            AROMA: 1,
            CAMO: 1,
            CAROM: 1,
            CHARM: 1,
            CHROMA: 1,
            COACHMAN: 1,
            COMA: 1,
            COMMA: 1,
            COMMON: 1,
            CRAM: 1,
            HARM: 1,
            MACARON: 1,
            MACAROON: 1,
            MACHO: 1,
            MACRO: 1,
            MACRON: 1,
            MAMA: 1,
            MAMMA: 1,
            MAMMON: 1,
            MANNA: 1,
            MANOR: 1,
            MARACA: 1,
            MARCH: 1,
            MARM: 1,
            MAROON: 1,
            MOAN: 1,
            MOCHA: 1,
            MOMMA: 1,
            MONARCH: 1,
            MONO: 1,
            MOOCH: 1,
            MOON: 1,
            MOOR: 1,
            MORN: 1,
            MORON: 1,
            NONCOM: 1,
            NORM: 1,
            ROAM: 1,
            ROMCOM: 1,
            ROOM: 1
        }
    },
    {
        letters: {
            middle: "C",
            otherSix: ["A", "I", "L", "M", "N", "R"]
        },
        answers: {
            ACACIA: 1,
            ACAI: 1,
            ACCLAIM: 1,
            ALMANAC: 1,
            ARCANA: 1,
            CAIMAN: 1,
            CAIRN: 1,
            CALAMARI: 1,
            CALL: 1,
            CALLA: 1,
            CALM: 1,
            CAMARILLA: 1,
            CANAL: 1,
            CANCAN: 1,
            CARNAL: 1,
            CILIA: 1,
            CIRCA: 1,
            CIRRI: 1,
            CLAIM: 1,
            CLAM: 1,
            CLAN: 1,
            CLINIC: 1,
            CLINICAL: 1,
            CLINICIAN: 1,
            CRAM: 1,
            CRANIA: 1,
            CRANIAL: 1,
            CRIMINAL: 1,
            INIMICAL: 1,
            LACRIMAL: 1,
            LAIC: 1,
            LAICAL: 1,
            LILAC: 1,
            MALIC: 1,
            MANCALA: 1,
            MANIAC: 1,
            MANIACAL: 1,
            MANIC: 1,
            MARACA: 1,
            MICA: 1,
            MIMIC: 1,
            MINICAM: 1,
            MINICAR: 1,
            NARC: 1,
            NIACIN: 1,
            RACIAL: 1,
            RAILCAR: 1,
            RICIN: 1
        }
    },
    {
        letters: {
            middle: "L",
            otherSix: ["B", "D", "F", "I", "N", "O"]
        },
        answers: {
            BIFOLD: 1,
            BILL: 1,
            BILLFOLD: 1,
            BILLION: 1,
            BLIN: 1,
            BLIND: 1,
            BLINDFOLD: 1,
            BLINI: 1,
            BLOB: 1,
            BLOND: 1,
            BLOOD: 1,
            BOIL: 1,
            BOLD: 1,
            BOLL: 1,
            BOLO: 1,
            DILDO: 1,
            DILL: 1,
            DOLL: 1,
            FILL: 1,
            FLOOD: 1,
            FOIL: 1,
            FOLD: 1,
            FOLIO: 1,
            FOOL: 1,
            IDOL: 1,
            INFILL: 1,
            LIBIDO: 1,
            LION: 1,
            LOBO: 1,
            LOIN: 1,
            LOLL: 1,
            LOON: 1,
            NONILLION: 1,
            OLIO: 1
        }
    },
    {
        letters: {
            middle: "F",
            otherSix: ["A", "C", "E", "L", "P", "T"]
        },
        answers: {
            AFFECT: 1,
            ALFALFA: 1,
            CAFE: 1,
            CALF: 1,
            CLEF: 1,
            CLEFT: 1,
            EFFACE: 1,
            EFFECT: 1,
            EFFETE: 1,
            FACE: 1,
            FACEPLATE: 1,
            FACET: 1,
            FACT: 1,
            FALAFEL: 1,
            FALL: 1,
            FATAL: 1,
            FATE: 1,
            FEAT: 1,
            FECAL: 1,
            FEEL: 1,
            FEET: 1,
            FELL: 1,
            FELLA: 1,
            FELLATE: 1,
            FELT: 1,
            FETA: 1,
            FETAL: 1,
            FETE: 1,
            FETTLE: 1,
            FLAP: 1,
            FLAT: 1,
            FLEA: 1,
            FLEE: 1,
            FLEECE: 1,
            FLEET: 1,
            LEAF: 1,
            LEAFLET: 1,
            LEFT: 1,
            PELF: 1,
            PFFT: 1,
            TAFFETA: 1
        }
    },
    {
        letters: {
            middle: "E",
            otherSix: ["A", "C", "L", "T", "Y", "Z"]
        },
        answers: {
            ACETAL: 1,
            ACETATE: 1,
            ALLELE: 1,
            ALLEY: 1,
            ALLEYCAT: 1,
            AZALEA: 1,
            CATALYZE: 1,
            CATTLE: 1,
            CELL: 1,
            CLAYEY: 1,
            CLEAT: 1,
            CYCLE: 1,
            ECLAT: 1,
            EELY: 1,
            ELATE: 1,
            ELECT: 1,
            ELECTEE: 1,
            EYELET: 1,
            LACE: 1,
            LACTATE: 1,
            LACTEAL: 1,
            LATE: 1,
            LATELY: 1,
            LATTE: 1,
            LAYETTE: 1,
            LAZE: 1,
            TACET: 1,
            TALE: 1,
            TATTLE: 1,
            TATTLETALE: 1,
            TEAL: 1,
            TEAT: 1,
            TELL: 1,
            TELLTALE: 1,
            YELL: 1,
            ZEAL: 1,
            ZETA: 1
        }
    }
]

export default arrayOfAnswers;
