let arrayOfAnswers = [
    {
        letters: {
            middle: "A",
            otherSix: ["C", "F", "I", "L", "R", "Y"]
        },
        answers: {
            ACACIA: 1,
            ACAI: 1,
            ACRYLIC: 1,
            ACYCLIC: 1,
            AFAR: 1,
            AFFAIR: 1,
            AFFRAY: 1,
            AIRILY: 1,
            AIRY: 1,
            ALFALFA: 1,
            ALLAY: 1,
            ALLY: 1,
            ARIA: 1,
            ARIL: 1,
            ARRAY: 1,
            CALCIFY: 1,
            CALF: 1,
            CALL: 1,
            CALLA: 1,
            CARRY: 1,
            CARRYALL: 1,
            CILIA: 1,
            CIRCA: 1,
            CLARIFY: 1,
            CLAY: 1,
            CYCLICAL: 1,
            CYCLICALLY: 1,
            FACIAL: 1,
            FACIALLY: 1,
            FAIL: 1,
            FAIR: 1,
            FAIRLY: 1,
            FAIRY: 1,
            FALL: 1,
            FALLACY: 1,
            FARCICAL: 1,
            FARCICALLY: 1,
            FILIAL: 1,
            FILIALLY: 1,
            FLAIL: 1,
            FLAIR: 1,
            FLAY: 1,
            FRAIL: 1,
            FRAY: 1,
            FRIAR: 1,
            FRIARY: 1,
            LACY: 1,
            LAIC: 1,
            LAICAL: 1,
            LAIR: 1,
            LIAR: 1,
            LILAC: 1,
            LIRA: 1,
            LYRICAL: 1,
            LYRICALLY: 1,
            RACIAL: 1,
            RACIALLY: 1,
            RACY: 1,
            RAIL: 1,
            RAILCAR: 1,
            RALLY: 1,
            RIAL: 1,
            RIFFRAFF: 1,
            RIYAL: 1
        }
    },
    {
        letters: {
            middle: "A",
            otherSix: ["B", "I", "L", "T", "V", "Y"]
        },
        answers: {
            ABILITY: 1,
            ABLY: 1,
            ALIBI: 1,
            ALIT: 1,
            ALLAY: 1,
            ALLY: 1,
            ATILT: 1,
            AVAIL: 1,
            AVAILABILITY: 1,
            AVAILABLY: 1,
            BABA: 1,
            BABY: 1,
            BAIL: 1,
            BAIT: 1,
            BALL: 1,
            BATTY: 1,
            BIALY: 1,
            BILABIAL: 1,
            BLAB: 1,
            BLABBY: 1,
            BLAT: 1,
            LABIA: 1,
            LABIAL: 1,
            LAITY: 1,
            LAVA: 1,
            LIABILITY: 1,
            LIVABILITY: 1,
            TABBY: 1,
            TABLA: 1,
            TAIL: 1,
            TALI: 1,
            TALL: 1,
            TALLY: 1,
            TATTY: 1,
            TIBIA: 1,
            TIBIAL: 1,
            VIABILITY: 1,
            VIABLY: 1,
            VIAL: 1,
            VILLA: 1,
            VITAL: 1,
            VITALITY: 1,
            VITALLY: 1

        }
    },
    {
        letters: {
            middle: "O",
            otherSix: ["A", "F", "H", "L", "T", "Y"]
        },
        answers: {
            AFLOAT: 1,
            AFOOT: 1,
            AHOY: 1,
            ALLOT: 1,
            ALLOY: 1,
            ALOFT: 1,
            ALOHA: 1,
            ALOOF: 1,
            ALOOFLY: 1,
            ALTO: 1,
            ATOLL: 1,
            AYATOLLAH: 1,
            FALLOFF: 1,
            FLATFOOT: 1,
            FLOAT: 1,
            FLOATY: 1,
            FOAL: 1,
            FOLLY: 1,
            FOOL: 1,
            FOOT: 1,
            FOOTFALL: 1,
            HALO: 1,
            HAYLOFT: 1,
            HOLLY: 1,
            HOLT: 1,
            HOLY: 1,
            HOOF: 1,
            HOOT: 1,
            HOTFOOT: 1,
            HOTLY: 1,
            LAYOFF: 1,
            LOAF: 1,
            LOATH: 1,
            LOATHLY: 1,
            LOFT: 1,
            LOFTY: 1,
            LOLL: 1,
            LOOFA: 1,
            LOOFAH: 1,
            LOOT: 1,
            LOTTO: 1,
            LOYAL: 1,
            LOYALLY: 1,
            LOYALTY: 1,
            OATH: 1,
            OATY: 1,
            OFFAL: 1,
            TALLYHO: 1,
            TATTOO: 1,
            TOLL: 1,
            TOOL: 1,
            TOOT: 1,
            TOOTH: 1,
            TOOTHY: 1,
            TOTAL: 1,
            TOTALLY: 1,
            YAHOO: 1,
            YOOHOO: 1
        }
    },
    {
        letters: {
            middle: "D",
            otherSix: ["A", "L", "N", "R", "U", "Y"]
        },
        answers: {
            DADDY: 1,
            DALLY: 1,
            DANDY: 1,
            DARN: 1,
            DRAY: 1,
            DRYAD: 1,
            DRYLAND: 1,
            DRYLY: 1,
            DUAL: 1,
            DUALLY: 1,
            DULL: 1,
            DULLARD: 1,
            DULLY: 1,
            DULY: 1,
            DYAD: 1,
            LADY: 1,
            LAND: 1,
            LANDAU: 1,
            LANDLADY: 1,
            LANYARD: 1,
            LARD: 1,
            LAUD: 1,
            LAUNDRY: 1,
            NADA: 1,
            RADAR: 1,
            RAND: 1,
            RANDY: 1,
            RUDDY: 1,
            UNDULY: 1,
            YARD: 1
        }
    },
    {
        letters: {
            middle: "H",
            otherSix: ["A", "C", "D", "N", "O", "W"]
        },
        answers: {
            ACHOO: 1,
            ANCHO: 1,
            CHAD: 1,
            CHAW: 1,
            CHOW: 1,
            COACH: 1,
            COHO: 1,
            CONCH: 1,
            COWHAND: 1,
            DACHA: 1,
            HAND: 1,
            HODAD: 1,
            HONCHO: 1,
            HOOCH: 1,
            HOOD: 1,
            HOODOO: 1,
            HOWDAH: 1,
            NACHO: 1,
            NOHOW: 1,
            WAHOO: 1,
            WHOA: 1,
            WOOHOO: 1
        }
    },
    {
        letters: {
            middle: "T",
            otherSix: ["H", "I", "L", "M", "N", "O"]
        },
        answers: {
            HILT: 1,
            HINT: 1,
            HOLT: 1,
            HOOT: 1,
            INTO: 1,
            LILT: 1,
            LIMIT: 1,
            LINT: 1,
            LITHO: 1,
            LOOT: 1,
            LOTION: 1,
            LOTTO: 1,
            MILLIONTH: 1,
            MINT: 1,
            MITT: 1,
            MOLT: 1,
            MONOLITH: 1,
            MONTH: 1,
            MOONLIT: 1,
            MOOT: 1,
            MOTH: 1,
            MOTION: 1,
            MOTTO: 1,
            NINTH: 1,
            NOTION: 1,
            OMIT: 1,
            ONTO: 1,
            THIN: 1,
            TILL: 1,
            TILT: 1,
            TINT: 1,
            TOIL: 1,
            TOLL: 1,
            TOMTIT: 1,
            TOOL: 1,
            TOON: 1,
            TOOT: 1,
            TOOTH: 1
        }
    },
    {
        letters: {
            middle: "M",
            otherSix: ["A", "D", "G", "I", "P", "R"]
        },
        answers: {
            AMID: 1,
            ARMADA: 1,
            DAMP: 1,
            DIAGRAM: 1,
            DRAM: 1,
            DRAMA: 1,
            GAMMA: 1,
            GIMP: 1,
            GRAM: 1,
            GRAMMA: 1,
            GRAMMAR: 1,
            GRAMP: 1,
            GRAMPA: 1,
            GRIM: 1,
            IMAM: 1,
            IMPAIR: 1,
            MADAM: 1,
            MAGI: 1,
            MAGMA: 1,
            MAID: 1,
            MAIM: 1,
            MAMA: 1,
            MAMMA: 1,
            MARM: 1,
            MIDAIR: 1,
            MIDI: 1,
            PAMPA: 1,
            PARADIGM: 1,
            PIMP: 1,
            PRAM: 1,
            PRIM: 1,
            PRIMP: 1,
            RAMADA: 1,
            RAMP: 1
        }
    },
    {
        letters: {
            middle: "B",
            otherSix: ["A", "C", "I", "K", "R", "T"]
        },
        answers: {
            ABACI: 1,
            ABACK: 1,
            ARABICA: 1,
            BABA: 1,
            BABKA: 1,
            BACCARAT: 1,
            BACK: 1,
            BACKBIT: 1,
            BACKTRACK: 1,
            BAIT: 1,
            BARB: 1,
            BARBARIC: 1,
            BARIATRIC: 1,
            BARK: 1,
            BARRACK: 1,
            BATIK: 1,
            BICARB: 1,
            BRAT: 1,
            BRIAR: 1,
            BRICK: 1,
            BRICKBAT: 1,
            CARB: 1,
            CIABATTA: 1,
            CRAB: 1,
            CRIB: 1,
            KICKBACK: 1,
            RABBI: 1,
            RABBIT: 1,
            TIBIA: 1
        }
    }
]

export default arrayOfAnswers;
